# Server
server.port=8080

# database Configuration
spring.datasource.url= select url
spring.datasource.username= select username
spring.datasource.password= select password
spring.jpa.hibernate.ddl-auto=update

spring.ai.openai.base-url=select url
spring.ai.openai.api-key= api key
spring.ai.openai.chat.options.model= 

# GitHub Configuration
github.api.token= github api token