# Server
server.port=8080

# database Configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.api-key= api key
spring.ai.openai.chat.options.model=

# GitHub Configuration
github.api.token= github api token